<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\IdentityNotes.Data.Models\IdentityNotes.Data.Models.csproj" />
      <ProjectReference Include="..\IdentityNotes.Data\IdentityNotes.Data.csproj" />
      <ProjectReference Include="..\IdentityNotes.GCommon\IdentityNotes.GCommon.csproj" />
      <ProjectReference Include="..\IdentityNotes.ViewModels\IdentityNotes.ViewModels.csproj" />
    </ItemGroup>

</Project>
