<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <UserSecretsId>aspnet-IdentityNotes-4642a17d-399c-4137-a43c-df1366057cd6</UserSecretsId>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore" Version="8.0.24"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.EntityFrameworkCore" Version="8.0.24"/>
        <PackageReference Include="Microsoft.AspNetCore.Identity.UI" Version="8.0.24"/>
        <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24"/>
        <PackageReference Include="Microsoft.VisualStudio.Web.CodeGeneration.Design" Version="8.0.24" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\IdentityNotes.Data\IdentityNotes.Data.csproj" />
      <ProjectReference Include="..\IdentityNotes.Service.Core\IdentityNotes.Service.Core.csproj" />
      <ProjectReference Include="..\IdentityNotes.ViewModels\IdentityNotes.ViewModels.csproj" />
    </ItemGroup>

</Project>
