// <auto-generated />
using System;
using GameZone.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GameZone.Migrations
{
    [DbContext(typeof(GameDbContext))]
    partial class GameDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GameZone.Data.Models.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("GenreId")
                        .HasColumnType("int");

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("PublisherName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateOnly>("ReleasedOn")
                        .HasColumnType("DATE");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.HasIndex("GenreId");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "A legendary real-time strategy game that defined competitive esports.",
                            GenreId = 6,
                            ImageUrl = "https://www.pcguide.com/wp-content/uploads/2022/07/Starcraft-2-system-requirements.jpg",
                            PublisherName = "Blizzard Entertainment",
                            ReleasedOn = new DateOnly(1998, 3, 31),
                            Title = "StarCraft"
                        },
                        new
                        {
                            Id = 2,
                            Description = "An open-world action game offering freedom, crime, and unforgettable characters.",
                            GenreId = 1,
                            ImageUrl = "https://w0.peakpx.com/wallpaper/409/681/HD-wallpaper-grand-theft-auto-grand-theft-auto-v.jpg",
                            PublisherName = "Rockstar Games",
                            ReleasedOn = new DateOnly(2013, 9, 17),
                            Title = "Grand Theft Auto V"
                        },
                        new
                        {
                            Id = 3,
                            Description = "A realistic rally racing game focused on precision, terrain, and driving skill.",
                            GenreId = 5,
                            ImageUrl = "https://www.motorsportmagazine.com/wp-content/uploads/2025/02/Scalextric-Colin-McRae-800x450.jpg",
                            PublisherName = "Codemasters",
                            ReleasedOn = new DateOnly(2002, 9, 27),
                            Title = "Colin McRae Rally 5"
                        });
                });

            modelBuilder.Entity("GameZone.Data.Models.Genre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Genres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Action"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Adventure"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Fighting"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Sports"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Racing"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Strategy"
                        });
                });

            modelBuilder.Entity("GameZone.Data.Models.Game", b =>
                {
                    b.HasOne("GameZone.Data.Models.Genre", "Genre")
                        .WithMany("Games")
                        .HasForeignKey("GenreId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Genre");
                });

            modelBuilder.Entity("GameZone.Data.Models.Genre", b =>
                {
                    b.Navigation("Games");
                });
#pragma warning restore 612, 618
        }
    }
}
