// <auto-generated />
using System;
using GarageApp.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace GarageApp.Migrations
{
    [DbContext(typeof(GarageDbContext))]
    [Migration("20260117155203_SeedInitialCarsAndGarages")]
    partial class SeedInitialCarsAndGarages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("GarageApp.Models.Car", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("BodyStyle")
                        .HasColumnType("int");

                    b.Property<Guid>("GarageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsAvailable")
                        .HasColumnType("bit");

                    b.Property<string>("Make")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GarageId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            Id = new Guid("d542460e-235c-435d-8a6a-30918ce3a8a5"),
                            BodyStyle = 5,
                            GarageId = new Guid("a0556d26-3224-4568-93e4-8ba997308f04"),
                            IsAvailable = true,
                            Make = "BMW",
                            Model = "320d",
                            Year = 2007
                        },
                        new
                        {
                            Id = new Guid("aa701bd7-c722-42db-a393-3f1b41f9bdba"),
                            BodyStyle = 1,
                            GarageId = new Guid("a0556d26-3224-4568-93e4-8ba997308f04"),
                            IsAvailable = false,
                            Make = "Audi",
                            Model = "A4",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("dc266079-c3ac-4046-a672-a3c0b0bc6975"),
                            BodyStyle = 2,
                            GarageId = new Guid("5ae2fdda-84dd-4d9d-a09e-e4b180e507c5"),
                            IsAvailable = true,
                            Make = "Volkswagen",
                            Model = "Golf",
                            Year = 2020
                        },
                        new
                        {
                            Id = new Guid("d4d2dab1-a742-4c8a-bb63-76cc86f016ac"),
                            BodyStyle = 1,
                            GarageId = new Guid("5ae2fdda-84dd-4d9d-a09e-e4b180e507c5"),
                            IsAvailable = true,
                            Make = "Toyota",
                            Model = "Corolla",
                            Year = 2021
                        },
                        new
                        {
                            Id = new Guid("ddb7b8fb-a81d-44e5-a2eb-7d748e090152"),
                            BodyStyle = 1,
                            GarageId = new Guid("bb0ef97b-d3a7-4a57-b39b-98c15ee5758c"),
                            IsAvailable = false,
                            Make = "Mercedes-Benz",
                            Model = "C220",
                            Year = 2017
                        },
                        new
                        {
                            Id = new Guid("9c048e12-c131-4a5e-85af-c0d374bbe04b"),
                            BodyStyle = 2,
                            GarageId = new Guid("bb0ef97b-d3a7-4a57-b39b-98c15ee5758c"),
                            IsAvailable = true,
                            Make = "Ford",
                            Model = "Focus",
                            Year = 2016
                        },
                        new
                        {
                            Id = new Guid("78ca1339-45e9-4585-8d7e-ea699e6488c2"),
                            BodyStyle = 8,
                            GarageId = new Guid("a0556d26-3224-4568-93e4-8ba997308f04"),
                            IsAvailable = true,
                            Make = "Mazda",
                            Model = "CX-5",
                            Year = 2022
                        },
                        new
                        {
                            Id = new Guid("ca9d2135-e400-4684-9eb5-5232c466f428"),
                            BodyStyle = 5,
                            GarageId = new Guid("5ae2fdda-84dd-4d9d-a09e-e4b180e507c5"),
                            IsAvailable = true,
                            Make = "Skoda",
                            Model = "Octavia",
                            Year = 2019
                        },
                        new
                        {
                            Id = new Guid("9623f701-ac46-4a9a-9863-0831190da302"),
                            BodyStyle = 3,
                            GarageId = new Guid("bb0ef97b-d3a7-4a57-b39b-98c15ee5758c"),
                            IsAvailable = false,
                            Make = "Honda",
                            Model = "Civic",
                            Year = 2018
                        },
                        new
                        {
                            Id = new Guid("f93dc41c-45a9-40b4-b4b6-bc720ada9c29"),
                            BodyStyle = 8,
                            GarageId = new Guid("a0556d26-3224-4568-93e4-8ba997308f04"),
                            IsAvailable = true,
                            Make = "Hyundai",
                            Model = "Tucson",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("GarageApp.Models.Garage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("GarageApp");

                    b.HasData(
                        new
                        {
                            Id = new Guid("a0556d26-3224-4568-93e4-8ba997308f04"),
                            Location = "Sofia Centre",
                            Name = "Sofia Central Garage"
                        },
                        new
                        {
                            Id = new Guid("5ae2fdda-84dd-4d9d-a09e-e4b180e507c5"),
                            Location = "Sofia, Balkan Star North",
                            Name = "Balkan Star North Garage"
                        },
                        new
                        {
                            Id = new Guid("bb0ef97b-d3a7-4a57-b39b-98c15ee5758c"),
                            Location = "Sofia, Porsche Sofia West",
                            Name = "Porsche Sofia West Garage"
                        });
                });

            modelBuilder.Entity("GarageApp.Models.Car", b =>
                {
                    b.HasOne("GarageApp.Models.Garage", "Garage")
                        .WithMany("Cars")
                        .HasForeignKey("GarageId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Garage");
                });

            modelBuilder.Entity("GarageApp.Models.Garage", b =>
                {
                    b.Navigation("Cars");
                });
#pragma warning restore 612, 618
        }
    }
}
