// <auto-generated />
using System;
using EventManager.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EventManager.Migrations
{
    [DbContext(typeof(EventDbContext))]
    partial class EventDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EventManager.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Conference"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Workshop"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Seminar"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Training"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Meetup"
                        },
                        new
                        {
                            Id = 6,
                            Name = "Hackathon"
                        },
                        new
                        {
                            Id = 7,
                            Name = "Webinar"
                        },
                        new
                        {
                            Id = 8,
                            Name = "Bootcamp"
                        });
                });

            modelBuilder.Entity("EventManager.Models.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("MaxParticipants")
                        .HasColumnType("int");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Events");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Description = "A conference covering the fundamentals of ASP.NET Core MVC.",
                            EndDate = new DateTime(2026, 3, 16, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 300,
                            StartDate = new DateTime(2026, 3, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "ASP.NET Core Fundamentals Conference"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Description = "Topics: MVC, REST, validation, and security basics for web apps.",
                            EndDate = new DateTime(2026, 5, 21, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 400,
                            StartDate = new DateTime(2026, 5, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Modern Web Development Conference"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 2,
                            Description = "Hands-on workshop focused on model binding and validation.",
                            EndDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 40,
                            StartDate = new DateTime(2026, 4, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Model Binding and Validation Workshop"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Description = "Build forms with tag helpers and display validation messages properly.",
                            EndDate = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 35,
                            StartDate = new DateTime(2026, 4, 24, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Razor Forms Workshop"
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 3,
                            Description = "How to keep controller actions small and predictable with ModelState.",
                            EndDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 120,
                            StartDate = new DateTime(2026, 6, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Clean Controllers Seminar"
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 3,
                            Description = "Server-side validation patterns and common mistakes in MVC apps.",
                            EndDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 120,
                            StartDate = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Validation Best Practices Seminar"
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 4,
                            Description = "DbContext, migrations, relationships, and seeding essentials.",
                            EndDate = new DateTime(2026, 2, 18, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 80,
                            StartDate = new DateTime(2026, 2, 17, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "EF Core Essentials Training"
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 4,
                            Description = "Practice form submissions, invalid model states, and error rendering.",
                            EndDate = new DateTime(2026, 7, 8, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 70,
                            StartDate = new DateTime(2026, 7, 7, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Testing MVC Forms Training"
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 5,
                            Description = "Community meetup: mini talks and networking for .NET developers.",
                            EndDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 150,
                            StartDate = new DateTime(2026, 3, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Sofia .NET Meetup"
                        },
                        new
                        {
                            Id = 10,
                            CategoryId = 5,
                            Description = "Students present their projects and discuss common issues and fixes.",
                            EndDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 150,
                            StartDate = new DateTime(2026, 5, 9, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "Student Projects Meetup"
                        },
                        new
                        {
                            Id = 11,
                            CategoryId = 6,
                            Description = "Build a small MVC app with validation rules under time constraints.",
                            EndDate = new DateTime(2026, 8, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            MaxParticipants = 60,
                            StartDate = new DateTime(2026, 8, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Title = "MVC Mini Hackathon"
                        });
                });

            modelBuilder.Entity("EventManager.Models.Registration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<string>("ParticipantName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("Registrations");
                });

            modelBuilder.Entity("EventManager.Models.Event", b =>
                {
                    b.HasOne("EventManager.Models.Category", "Category")
                        .WithMany("Events")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("EventManager.Models.Registration", b =>
                {
                    b.HasOne("EventManager.Models.Event", "Event")
                        .WithMany("Registrations")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EventManager.Models.Category", b =>
                {
                    b.Navigation("Events");
                });

            modelBuilder.Entity("EventManager.Models.Event", b =>
                {
                    b.Navigation("Registrations");
                });
#pragma warning restore 612, 618
        }
    }
}
