// <auto-generated />
using System;
using BookShelf.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BookShelf.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.23")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BookShelf.Models.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Country")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("79f1f7bd-8745-4c39-b4a0-cfec65a33dce"),
                            Name = "George Orwell"
                        },
                        new
                        {
                            Id = new Guid("665a9d35-bfad-453a-a38d-67858d501bb1"),
                            Country = "Russia",
                            Name = "Fyodor Dostoevsky"
                        },
                        new
                        {
                            Id = new Guid("66a2348d-b60c-4db6-ad02-b341f086892d"),
                            Country = "Britain",
                            Name = "Jane Austen"
                        },
                        new
                        {
                            Id = new Guid("8e14aa56-8098-4a50-bcfd-e694f018c29a"),
                            Country = "USA",
                            Name = "Ernest Hemingway"
                        },
                        new
                        {
                            Id = new Guid("5736a045-bd63-408c-a7eb-bdcaacf9e63e"),
                            Country = "Colombia",
                            Name = "Gabriel García Márquez"
                        });
                });

            modelBuilder.Entity("BookShelf.Models.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("661ee1c6-e927-429a-a225-c90339a41717"),
                            AuthorId = new Guid("79f1f7bd-8745-4c39-b4a0-cfec65a33dce"),
                            Title = "1984",
                            Year = 1949
                        },
                        new
                        {
                            Id = new Guid("91eb90d5-72ec-4362-91d5-db0488e466ca"),
                            AuthorId = new Guid("79f1f7bd-8745-4c39-b4a0-cfec65a33dce"),
                            Title = "Animal Farm",
                            Year = 1945
                        },
                        new
                        {
                            Id = new Guid("a597ec9c-c3ae-4d91-b62b-0df4c9046892"),
                            AuthorId = new Guid("665a9d35-bfad-453a-a38d-67858d501bb1"),
                            Title = "Crime and Punishment",
                            Year = 1866
                        },
                        new
                        {
                            Id = new Guid("e20b5bc9-b1d1-43bc-9ba2-cd5c1f8df9d6"),
                            AuthorId = new Guid("665a9d35-bfad-453a-a38d-67858d501bb1"),
                            Title = "The Brothers Karamazov",
                            Year = 1880
                        },
                        new
                        {
                            Id = new Guid("e7de82ed-bbdf-4b85-aa1a-56ff33f415ab"),
                            AuthorId = new Guid("66a2348d-b60c-4db6-ad02-b341f086892d"),
                            Title = "Pride and Prejudice",
                            Year = 1813
                        },
                        new
                        {
                            Id = new Guid("5d058393-fce5-459b-8cad-0873e9704411"),
                            AuthorId = new Guid("8e14aa56-8098-4a50-bcfd-e694f018c29a"),
                            Title = "The Old Man and the Sea",
                            Year = 1952
                        },
                        new
                        {
                            Id = new Guid("35483dcf-685b-4ac1-ae01-e02638ecd5f0"),
                            AuthorId = new Guid("5736a045-bd63-408c-a7eb-bdcaacf9e63e"),
                            Title = "One Hundred Years of Solitude",
                            Year = 1967
                        },
                        new
                        {
                            Id = new Guid("e7acaae5-0acb-4b1b-a818-447a19373862"),
                            AuthorId = new Guid("5736a045-bd63-408c-a7eb-bdcaacf9e63e"),
                            Title = "Love in the Time of Cholera",
                            Year = 1985
                        });
                });

            modelBuilder.Entity("BookShelf.Models.Book", b =>
                {
                    b.HasOne("BookShelf.Models.Author", "Author")
                        .WithMany("Books")
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });

            modelBuilder.Entity("BookShelf.Models.Author", b =>
                {
                    b.Navigation("Books");
                });
#pragma warning restore 612, 618
        }
    }
}
