<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <RootNamespace>Homies.Service.Core</RootNamespace>
    </PropertyGroup>

    <ItemGroup>
      <ProjectReference Include="..\Homies.Data.Models\Homies.Data.Models.csproj" />
      <ProjectReference Include="..\Homies.Data\Homies.Data.csproj" />
      <ProjectReference Include="..\Homies.ViewModels\Homies.ViewModels.csproj" />
    </ItemGroup>

</Project>
